Tables
Granola-Team/mina-on-chain-voting pull request #258
Opened 2023-09-15 18:20 UTC by jstavh

Make each whole row clickable.

2023-09-15 19:17 UTC, jstavh commented
This works. Just have to appease the testing code.

2023-09-15 19:49 UTC, jstavh commented
@52 Requested Max's review. next/link work won't because it is in a table. Using <a> with <Link> is legacy methods. Resorted to useRouter to allow rows to be clickable. This succeeds in the proposal (main) table but continues into the votes (pages) tables.

2023-09-18 12:03 UTC, 52 requested changes
Couple additional points:
- Delete the `saving-test` directory and move the tests back. (No need to move any files around)

- Since you've made a change to the core component, the `votes-table` will now also have clickable rows, that route to someplace wrong. This would also need to be addressed.

2023-09-18 12:03 UTC, 52 commented on web/components/saving-tests/mockNextRouter.ts
> +}
This shouldn't be necessary, use features provided by `next-router-mock`

2023-09-18 16:46 UTC, jstavh commented
> Couple additional points:
> 
> * Delete the `saving-test` directory and move the tests back. (No need to move any files around)
> * Since you've made a change to the core component, the `votes-table` will now also have clickable rows, that route to someplace wrong. This would also need to be addressed.

@52 I've tried your suggestions and implemented them in the most recent commit but getting errors, such as `Property 'id' does not exist on type 'T'.ts(2339)`

2023-09-18 21:50 UTC, 52 commented
> > Couple additional points:
> > 
> > * Delete the `saving-test` directory and move the tests back. (No need to move any files around)
> > * Since you've made a change to the core component, the `votes-table` will now also have clickable rows, that route to someplace wrong. This would also need to be addressed.
> 
> @52 I've tried your suggestions already but implemented them again in the most recent commit but getting errors, such as `Property 'id' does not exist on type 'T'.ts(2339)`

Yes, you're accessing a property on a generic type, TS cannot guarantee that it exists.
You need to modify the types to narrow it down.

2023-09-18 22:40 UTC, jstavh commented
> > > Couple additional points:
> > > 
> > > * Delete the `saving-test` directory and move the tests back. (No need to move any files around)
> > > * Since you've made a change to the core component, the `votes-table` will now also have clickable rows, that route to someplace wrong. This would also need to be addressed.
> > 
> > 
> > @52 I've tried your suggestions already but implemented them again in the most recent commit but getting errors, such as `Property 'id' does not exist on type 'T'.ts(2339)`
> 
> Yes, you're accessing a property on a generic type, TS cannot guarantee that it exists. You need to modify the types to narrow it down.
> 
> As for the issue of the "click-ability" being shared between votes & proposal tables: You'll have to do a couple things to make this work:
> 
> 1. Create an additional prop called "variant" thats of type `DataTableVariant`
> 
> ```ts
> ...
> export const DataTableVariants = ['proposal', 'vote'] as const;
> export type DataTableVariant = (typeof DataTableVariants)[number];
> ```
> 
> 2. Pass the correct variant as props at each usage site. (ProposalTable & VotesTable)
> 3. Inside the core component, conditionally render the TableRow depending on which variant is passed in.
> 
> On the right track, though! 👍

@52 Thanks, Max! I should've stuck with this path longer. Appreciate the notes.

2023-09-19 00:43 UTC, jstavh commented
> > > > Couple additional points:
> > > > 
> > > > * Delete the `saving-test` directory and move the tests back. (No need to move any files around)
> > > > * Since you've made a change to the core component, the `votes-table` will now also have clickable rows, that route to someplace wrong. This would also need to be addressed.
> > > 
> > > 
> > > @52 I've tried your suggestions already but implemented them again in the most recent commit but getting errors, such as `Property 'id' does not exist on type 'T'.ts(2339)`
> > 
> > 
> > Yes, you're accessing a property on a generic type, TS cannot guarantee that it exists. You need to modify the types to narrow it down.
> > As for the issue of the "click-ability" being shared between votes & proposal tables: You'll have to do a couple things to make this work:
> > 
> > 1. Create an additional prop called "variant" thats of type `DataTableVariant`
> > 
> > ```ts
> > ...
> > export const DataTableVariants = ['proposal', 'vote'] as const;
> > export type DataTableVariant = (typeof DataTableVariants)[number];
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 2. Pass the correct variant as props at each usage site. (ProposalTable & VotesTable)
> > 3. Inside the core component, conditionally render the TableRow depending on which variant is passed in.
> > 
> > On the right track, though! 👍
> 
> @52 Thanks, Max! I should've stuck with this path longer. Appreciate your notes.

@52 the prop isn't simply passed to the VotesTable. Adding `const votesWithIds = votes.map((vote, index) => ({ ...vote, id: index }));` fixes the data attribute but then the columns attribute columns similarily but less easily fixed unless we add an 'id' is one of the accessor keys, which I'm unsure yet if it is a good idea.

2023-09-19 19:34 UTC, jstavh commented
> > > > > Couple additional points:
> > > > > 
> > > > > * Delete the `saving-test` directory and move the tests back. (No need to move any files around)
> > > > > * Since you've made a change to the core component, the `votes-table` will now also have clickable rows, that route to someplace wrong. This would also need to be addressed.
> > > > 
> > > > 
> > > > @52 I've tried your suggestions already but implemented them again in the most recent commit but getting errors, such as `Property 'id' does not exist on type 'T'.ts(2339)`
> > > 
> > > 
> > > Yes, you're accessing a property on a generic type, TS cannot guarantee that it exists. You need to modify the types to narrow it down.
> > > As for the issue of the "click-ability" being shared between votes & proposal tables: You'll have to do a couple things to make this work:
> > > 
> > > 1. Create an additional prop called "variant" thats of type `DataTableVariant`
> > > 
> > > ```ts
> > > ...
> > > export const DataTableVariants = ['proposal', 'vote'] as const;
> > > export type DataTableVariant = (typeof DataTableVariants)[number];
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 
> > > 2. Pass the correct variant as props at each usage site. (ProposalTable & VotesTable)
> > > 3. Inside the core component, conditionally render the TableRow depending on which variant is passed in.
> > > 
> > > On the right track, though! 👍
> > 
> > 
> > @52 Thanks, Max! I should've stuck with this path longer. Appreciate your notes.
> 
> @52 the prop isn't simply passed to the VotesTable. Adding `const votesWithIds = votes.map((vote, index) => ({ ...vote, id: index }));` fixes the data attribute but then the columns attribute columns similarly but less easily fixed unless we add an 'id' is one of the accessor keys, which I'm unsure yet if it is a good idea.

@52 Solved :) by matching the expected type of the columns prop in the DataTable component to the columns being passed when using the VotesTable component.

2023-09-22 12:33 UTC, 52 commented on web/components/core/data-table.tsx
> +interface Props<T extends { id: number }, V> {
Remove `...extends { id: number }`

2023-09-22 12:36 UTC, 52 requested changes
Also, the following request is still needed:
- Delete the saving-test directory and move the tests back.

2023-09-22 12:36 UTC, 52 commented on web/components/core/data-table.tsx
> +interface Props<T extends { id: number }, V> {
Remove `...extends { id: number }`

2023-09-22 12:36 UTC, 52 commented on web/components/core/data-table.tsx
> +export const DataTable = <T extends { id: number }, V>({columns, columnVisibility, data, Toolbar, variant }: Props<T, V>) => {
Remove `...extends { id: number }`

2023-09-22 12:36 UTC, 52 commented on web/components/core/data-table.tsx
> +                    ? () => router.push(`/proposal/${row.original.id}/results/`)
Use `row.getValue("id")` instead of `row.original.id`

2023-09-22 12:36 UTC, 52 commented on web/components/saving-tests/spec-votes-table.tsx
> +
Remove this

2023-09-22 12:36 UTC, 52 commented on web/components/votes-table.tsx
> +const columns: ColumnDef<Props['votes'][number] & { id: number }>[] = [
Remove ` & { id: number }`

2023-09-22 12:36 UTC, 52 commented on web/components/votes-table.tsx
> +  const votesWithIds = votes.map((vote, index) => ({ ...vote, id: index }));
Remove this

2023-09-22 22:46 UTC, jstavh commented
@52 the code works, so can you elaborate on your edit revisions? The only thing that "does not work" are two tests, which look like they need more customization support beyond the fix we just deployed for Next 13's lack of support for `next-router-mock` (though supported by Next 11) and only released publicly https://github.com/scottrippey/next-router-mock/pull/105 two (2) days ago. As you wrote here https://github.com/Granola-Team/mina-on-chain-voting/pull/289 -- given this is just to add click-ability to rows, can we move forward from here?

2023-09-22 23:23 UTC, 52 commented
> @52 the code works, so can you elaborate on your edit revisions? The only thing that "does not work" are two tests, which look like they need more customization support beyond the fix we just deployed for Next 13's lack of support for `next-router-mock` (though supported by Next 11) and only released publicly [scottrippey/next-router-mock#105](https://github.com/scottrippey/next-router-mock/pull/105) two (2) days ago. As you wrote here #289 -- given this is just to add click-ability to rows, can we move forward from here?

Resolved offline, closing in favor of another approach.

2023-09-22 23:23 UTC, closed without merging